kumuluzee:
  name: artistsubscription-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  datasources:
    - jndi-name: jdbc/ArtistSubscriptionsDS
      connection-url: jdbc:postgresql://localhost:5435/artistsubscription
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
     # servlet:
     #   mapping: /health
     #   enabled: true
      checks:
        data-source-health-check:
          jndi-name: jdbc/ArtistSubscriptionsDS
  metrics:
      web-instrumentation:
        - name: metricsEndpoint
          url-pattern: /metrics/*
        - name: artistSubscriptionsEndpoint
          url-pattern: /v1/artistSubscriptions/*
#  config:
#    etcd:
#      hosts: http://192.168.99.100:2379
#  discovery:
#    etcd:
#      hosts: http://192.168.99.100:2379

 # rest-properties:
    #external-dependencies:
    #  band-service:
    #    enabled: true
